server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

eureka:
  client:
    register-with-eureka: false   # don't register itself
    fetch-registry: false         # don't fetch registry